POST http://admin:password@127.0.0.1:8081/auth/register
Content-Type: application/json

{
    "name": "Alice",
    "email": "user@test.xyz",
    "password": "password"
}

### clean up
GET http://admin:password@127.0.0.1:8081/admin/cleanup
