version: 3

tasks:
  generate:
    desc: Generate all code
    cmds:
      - sqlc generate
      - templ generate
      - tailwindcss -i ./static/css/input.css -o ./static/css/styles.css

  setup:
    desc: Install dependencies
    cmds:
      - go install github.com/pressly/goose/v3/cmd/goose@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/air-verse/air@latest

  release:
    desc: Release
    deps: [generate]
    cmds:
      - go test ./...
      - docker build -t corka149/rental:1.0.2 .
      - docker push corka149/rental:1.0.2
