# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: myadmin
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: test_rental_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    container: golang:1.22-bookworm

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        DB_HOST: "postgres"
        DB_PORT: "5432"
        DB_USER: "myadmin"
        DB_PASSWORD: "mypassword"
        DB_NAME: "test_rental_db"
